# Generated by Django 5.2.7 on 2025-10-09 15:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=255, verbose_name='Ссылка на Телеграм')),
                ('instagram', models.CharField(max_length=255, verbose_name='Ссылка на Инстаграм')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='Ссылка на Ватсап')),
                ('title_banner', models.CharField(max_length=155, verbose_name='Заголовка на Баннере')),
                ('title_banner_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка на Баннере')),
                ('title_banner_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка на Баннере')),
                ('description_banner', ckeditor.fields.RichTextField(verbose_name='Описание Баннера')),
                ('description_banner_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание Баннера')),
                ('description_banner_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание Баннера')),
                ('image_banner', models.ImageField(upload_to='settings', verbose_name='Фото на баннере')),
                ('about_title', models.CharField(max_length=155, verbose_name='Заголовка о нас')),
                ('about_title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка о нас')),
                ('about_title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка о нас')),
                ('description_about', ckeditor.fields.RichTextField(verbose_name='Описание О нас')),
                ('description_about_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание О нас')),
                ('description_about_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание О нас')),
                ('image_about1', models.ImageField(upload_to='about', verbose_name='Фото о нас')),
                ('image_about2', models.ImageField(upload_to='about', verbose_name='Фото о нас')),
                ('end_about', ckeditor.fields.RichTextField(verbose_name='Текст О нас')),
                ('end_about_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Текст О нас')),
                ('end_about_en', ckeditor.fields.RichTextField(null=True, verbose_name='Текст О нас')),
                ('title_catalog', models.CharField(max_length=155, verbose_name='Заголовка Каталог')),
                ('title_catalog_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка Каталог')),
                ('title_catalog_en', models.CharField(max_length=155, null=True, verbose_name='Заголовка Каталог')),
                ('review', models.CharField(max_length=155, verbose_name='Отзывы')),
                ('review_ru', models.CharField(max_length=155, null=True, verbose_name='Отзывы')),
                ('review_en', models.CharField(max_length=155, null=True, verbose_name='Отзывы')),
                ('description_review', ckeditor.fields.RichTextField(verbose_name='Описание отзывов')),
                ('description_review_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание отзывов')),
                ('description_review_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание отзывов')),
                ('text_footer', ckeditor.fields.RichTextField(verbose_name='Описание Футера')),
                ('text_footer_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание Футера')),
                ('text_footer_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание Футера')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки Сайта',
            },
        ),
    ]
