# Generated by Django 5.2.7 on 2025-10-09 15:29

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=False, verbose_name='В наличий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_type', models.CharField(choices=[('standard', 'Обычная доставка'), ('express', 'Быстрая доставка')], max_length=20, verbose_name='Способ доставки')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='Индекс')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма товаров')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('delivery_eta_hours', models.PositiveIntegerField(default=24, verbose_name='Минимальный срок, ч')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Желаемое время доставки')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Назначено на')),
                ('delivery_note', models.CharField(blank=True, max_length=255, verbose_name='Примечание по доставке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Оформленный заказ',
                'verbose_name_plural': 'Оформленные заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('fio_name', models.CharField(max_length=155, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=155, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=155, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Наши контакты',
                'verbose_name_plural': 'Наши контакты',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Дневной отчёт'), ('weekly', 'Недельный отчёт'), ('monthly', 'Месячный отчёт')], max_length=10, verbose_name='Тип отчёта')),
                ('total_orders', models.PositiveIntegerField(verbose_name='Количество заказов')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая выручка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отчёта')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('email', models.CharField(max_length=155, verbose_name='Почта')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')], default=5, verbose_name='Оценка (1–5)')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')], default=5, verbose_name='Оценка (1–5)')),
                ('is_favorites', models.BooleanField(default=False, verbose_name='В ИЗБРАННОЕ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='Имя клиента')),
                ('user_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('user_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма строки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.checkoutorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
