# Generated by Django 5.2.7 on 2025-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ckidka',
            field=models.CharField(default=1, max_length=155, verbose_name='Скидка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_sum',
            field=models.CharField(default=1, max_length=155, verbose_name='Общая цена'),
            preserve_default=False,
        ),
    ]
