# Generated by Django 5.2.7 on 2025-10-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_ckidka_product_total_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Модели')),
                ('is_active', models.BooleanField(default=False, verbose_name='В наличий')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='shop.modelsproduct', verbose_name='Модели'),
        ),
    ]
