# Generated by Django 5.2.7 on 2025-10-13 06:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_modelsproduct_product_model_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_product',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание продукта'),
            preserve_default=False,
        ),
    ]
