# Generated by Django 5.2.7 on 2025-10-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('email', models.CharField(max_length=155, verbose_name='Почта')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
