# Generated by Django 5.2.7 on 2025-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')], default=5, verbose_name='Оценка (1–5)'),
        ),
    ]
