# Generated by Django 5.2.7 on 2025-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_reviews_options_reviews_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Дневной отчёт'), ('weekly', 'Недельный отчёт'), ('monthly', 'Месячный отчёт')], max_length=10, verbose_name='Тип отчёта')),
                ('total_orders', models.PositiveIntegerField(verbose_name='Количество заказов')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая выручка')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отчёта')),
            ],
            options={
                'verbose_name': 'Отчёт по продажам',
                'verbose_name_plural': 'Отчёты по продажам',
                'ordering': ['-generated_at'],
            },
        ),
    ]
