# Generated by Django 5.2.7 on 2025-10-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_salesreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesReport',
            new_name='Report',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='generated_at',
            new_name='created_at',
        ),
    ]
