# Generated by Django 5.2.7 on 2025-10-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_salesreport_report_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
