# Generated by Django 5.2.7 on 2025-10-06 16:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_user_address_order_user_name_order_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=False, verbose_name='В наличий')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_favorites',
            field=models.BooleanField(default=False, verbose_name='В ИЗБРАННОЕ'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ (1)'), (2, '★★☆☆☆ (2)'), (3, '★★★☆☆ (3)'), (4, '★★★★☆ (4)'), (5, '★★★★★ (5)')], default=5, verbose_name='Оценка (1–5)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='shop.category', verbose_name='Категория'),
        ),
    ]
