# Generated by Django 5.2.7 on 2025-10-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_product_is_favorites_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_type', models.CharField(choices=[('standard', 'Обычная доставка'), ('express', 'Быстрая доставка')], max_length=20, verbose_name='Способ доставки')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='Индекс')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма товаров')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('delivery_eta_hours', models.PositiveIntegerField(default=24, verbose_name='Минимальный срок, ч')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Желаемое время доставки')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Назначено на')),
                ('delivery_note', models.CharField(blank=True, max_length=255, verbose_name='Примечание по доставке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Оформленный заказ',
                'verbose_name_plural': 'Оформленные заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма строки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.checkoutorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
