# Generated by Django 5.2.7 on 2025-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_visit_delete_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('fio_name', models.CharField(max_length=155, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=155, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=155, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Наши контакты',
                'verbose_name_plural': 'Наши контакты',
            },
        ),
    ]
